litrevu/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("reviews.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path

from . import views

# Namespace for the reviews app
app_name = 'reviews'

urlpatterns = [
    path('feed/', views.feed, name='home'),
    path('posts/', views.view_posts, name='view_posts'),
    path('tickets/create/', views.create_ticket, name='create_ticket'),
    path('tickets/<int:ticket_id>/edit/', views.edit_ticket, name='edit_ticket'),
    path('tickets/<int:ticket_id>/delete/', views.delete_ticket, name='delete_ticket'),
    path('tickets/<int:ticket_id>/reviews/create', views.create_ticket_review, name='create_ticket_review'),
    path('tickets/<int:ticket_id>/reviews/<int:review_id>/edit/', views.edit_ticket_review, name='edit_ticket_review'),
    path(
        'tickets/<int:ticket_id>/reviews/<int:review_id>/delete/',
        views.delete_ticket_review,
        name='delete_ticket_review',
    ),
    path('tickets-reviews/create/', views.create_ticket_and_review, name='create_ticket_and_review'),
    path('follow_users/', views.follow_users, name='follow_users'),
    path('unfollow_users/<int:user_id>', views.unfollow_users, name='unfollow_users'),
]

reviews/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from PIL import Image


class Review(models.Model):
    '''
    Model for a review.

    Attributes:
        headline (CharField): The headline of the review.
        body (TextField): The body of the review.
        rating (PositiveSmallIntegerField): The rating of the review.
        time_created (DateTimeField): The time the review was created.
        user (ForeignKey): The user who created the review.
        ticket (ForeignKey): The ticket the review is for.
    '''

    headline = models.CharField(max_length=128)
    body = models.TextField(max_length=8192, blank=True)
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    time_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ticket = models.ForeignKey("Ticket", on_delete=models.CASCADE)


class Ticket(models.Model):
    '''
    Model for a ticket.

    Attributes:
        title (CharField): The title of the ticket.
        description (TextField): The description of the ticket.
        image (ImageField): The image of the ticket.
        time_created (DateTimeField): The time the ticket was created.
        user (ForeignKey): The user who created the ticket.
    '''

    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048, blank=True)
    image = models.ImageField(null=True, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    IMAGE_MAX_SIZE = (800, 800)

    def resize_image(self):
        img = Image.open(self.image.path)
        img.thumbnail(self.IMAGE_MAX_SIZE)
        # save of the resized image in the filesystem
        # this is not the save() method of the model !
        img.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            self.resize_image()

reviews/forms.py
from django import forms

from . import models


class TicketForm(forms.ModelForm):
    '''
    Form for creating a new ticket.

    Attributes:
        title (CharField): The title of the ticket.
        description (TextField): The description of the ticket.
        image (ImageField): The image of the ticket.
    '''

    edit_ticket = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    title = forms.CharField(label="Titre", max_length=128, widget=forms.TextInput())
    description = forms.CharField(label="Description", max_length=2048, widget=forms.Textarea(), required=False)
    image = forms.ImageField(label="Image", required=False)

    class Meta:
        model = models.Ticket
        fields = ['title', 'description', 'image']


class DeleteTicketForm(forms.Form):
    '''
    Form for deleting a ticket.

    Attributes:
        delete_ticket (BooleanField): A boolean field that is used to delete a ticket.
    '''

    delete_ticket = forms.BooleanField(widget=forms.HiddenInput, initial=True)


class ReviewForm(forms.ModelForm):
    '''
    Form for creating a new review.

    Attributes:
        headline (CharField): The headline of the review.
        rating (ChoiceField): The rating of the review.
        body (CharField): The body of the review.
    '''

    edit_review = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    headline = forms.CharField(label="Titre", max_length=128, widget=forms.TextInput())
    rating = forms.ChoiceField(
        initial=1,
        label="Rating",
        widget=forms.RadioSelect(),
        choices=((1, "1 star"), (2, "2 stars"), (3, "3 stars"), (4, "4 stars"), (5, '5 stars')),
    )
    body = forms.CharField(label="Critique", max_length=8192, widget=forms.Textarea(), required=False)

    class Meta:
        model = models.Review
        fields = ['headline', 'rating', 'body']


class DeleteReviewForm(forms.Form):
    '''
    Form for deleting a review.

    Attributes:
        delete_review (BooleanField): A boolean field that is used to delete a review.
    '''

    delete_review = forms.BooleanField(widget=forms.HiddenInput, initial=True)


class FollowUsersForm(forms.Form):
    '''
    Form for following users.

    Attributes:
        followed_user (CharField): The user to follow.
    '''

    followed_user = forms.CharField(label=False, widget=forms.TextInput())

reviews/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect, get_object_or_404
from django.db import IntegrityError
from django.db.models import Value, CharField, Q
from django.core.paginator import Paginator

from itertools import chain

from authentication.models import User, UserFollows
from . import forms
from . import models


@login_required
def feed(request):
    # returns queryset of reviews for users followed by the current user
    followed_users = request.user.follows.all()
    reviews = models.Review.objects.filter(
        # the user who wrote the review is in the list of followed users
        Q(user__in=followed_users)
        |
        # the user who wrote the review is the current user
        Q(user=request.user)
    ).order_by('-time_created')
    reviews = reviews.annotate(content_type=Value('REVIEW', CharField()))

    # returns queryset of tickets for users followed by the current user
    tickets = models.Ticket.objects.filter(user__in=followed_users).order_by('-time_created')
    tickets = tickets.annotate(content_type=Value('TICKET', CharField()))

    # combine and sort the two types of posts
    posts = sorted(chain(reviews, tickets), key=lambda post: post.time_created, reverse=True)

    # Dectect if a follows user has already reviewed a ticket
    for post in posts:
        if post.content_type == 'TICKET':
            post.has_reviewed = models.Review.objects.filter(Q(ticket=post)).exists()

    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}

    return render(request, 'reviews/feed.html', context=context)


@login_required
def view_posts(request):
    # returns queryset of reviews
    reviews = models.Review.objects.filter(user=request.user)
    reviews = reviews.annotate(content_type=Value('REVIEW', CharField()))

    # returns queryset of tickets
    tickets = models.Ticket.objects.filter(user=request.user)
    tickets = tickets.annotate(content_type=Value('TICKET', CharField()))

    # combine and sort the two types of posts
    posts = sorted(chain(reviews, tickets), key=lambda post: post.time_created, reverse=True)

    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}

    return render(request, 'reviews/posts.html', context=context)


@login_required
@permission_required('reviews.add_ticket', raise_exception=True)
def create_ticket(request):
    ticket_form = forms.TicketForm()

    if request.method == 'POST':
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        if ticket_form.is_valid():
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            return redirect('reviews:view_posts')

    context = {'ticket_form': ticket_form}

    return render(request, 'reviews/create_ticket.html', context=context)


@login_required
@permission_required('reviews.change_ticket', raise_exception=True)
def edit_ticket(request, ticket_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id, user=request.user)
    edit_form = forms.TicketForm(instance=ticket)

    if request.method == 'POST':
        if 'edit_ticket' in request.POST:
            edit_form = forms.TicketForm(request.POST, request.FILES, instance=ticket)
            if edit_form.is_valid():
                edit_form.save()
                return redirect('reviews:view_posts')

    context = {'edit_form': edit_form}

    return render(request, 'reviews/edit_ticket.html', context=context)


@login_required
@permission_required('reviews.delete_ticket', raise_exception=True)
def delete_ticket(request, ticket_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id, user=request.user)
    delete_form = forms.DeleteTicketForm()

    if request.method == 'POST':
        if 'delete_ticket' in request.POST:
            delete_form = forms.DeleteTicketForm(request.POST)
            if delete_form.is_valid():
                ticket.delete()
                return redirect('reviews:view_posts')

    context = {
        'delete_form': delete_form,
        'ticket': ticket,
    }

    return render(request, 'reviews/delete_ticket.html', context=context)


@login_required
@permission_required('reviews.add_review', raise_exception=True)
def create_ticket_review(request, ticket_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    review_form = forms.ReviewForm()

    if request.method == 'POST':
        review_form = forms.ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.ticket = ticket
            review.save()
            return redirect('reviews:view_posts')

    context = {
        'review_form': review_form,
        'ticket': ticket,
    }

    return render(request, 'reviews/create_ticket_review.html', context=context)


@login_required
@permission_required('reviews.change_review', raise_exception=True)
def edit_ticket_review(request, ticket_id, review_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    review = get_object_or_404(models.Review, id=review_id, user=request.user)
    edit_form = forms.ReviewForm(instance=review)

    if request.method == 'POST':
        if 'edit_review' in request.POST:
            edit_form = forms.ReviewForm(request.POST, instance=review)
            if edit_form.is_valid():
                edit_form.save()
                return redirect('reviews:view_posts')

    context = {
        'edit_form': edit_form,
        'ticket': ticket,
    }

    return render(request, 'reviews/edit_ticket_review.html', context=context)


@login_required
@permission_required('reviews.delete_review', raise_exception=True)
def delete_ticket_review(request, ticket_id, review_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    review = get_object_or_404(models.Review, id=review_id, user=request.user)
    delete_form = forms.DeleteReviewForm()

    if request.method == 'POST':
        if 'delete_review' in request.POST:
            delete_form = forms.DeleteReviewForm(request.POST)
            if delete_form.is_valid():
                review.delete()
                return redirect('reviews:view_posts')

    context = {
        'delete_form': delete_form,
        'ticket': ticket,
        'review': review,
    }

    return render(request, 'reviews/delete_ticket_review.html', context=context)


@login_required
@permission_required(['reviews.add_ticket', 'reviews.add_review'], raise_exception=True)
def create_ticket_and_review(request):
    ticket_form = forms.TicketForm()
    review_form = forms.ReviewForm()

    if request.method == 'POST':
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        review_form = forms.ReviewForm(request.POST)

        if all([ticket_form.is_valid(), review_form.is_valid()]):
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.save()

            review = review_form.save(commit=False)
            review.user = request.user
            review.ticket = ticket
            review.save()

            return redirect('reviews:view_posts')

    context = {
        'ticket_form': ticket_form,
        'review_form': review_form,
    }

    return render(request, 'reviews/create_ticket_and_review.html', context=context)


@login_required
def follow_users(request):
    follow_form = forms.FollowUsersForm()

    if request.method == 'POST':
        follow_form = forms.FollowUsersForm(request.POST)

        if follow_form.is_valid():
            try:
                followed_user = User.objects.get(username=request.POST['followed_user'])
                if request.user == followed_user:
                    messages.error(request, 'Vous ne pouvez pas vous abonner à vous-même!')
                else:
                    try:
                        UserFollows.objects.create(user=request.user, followed_user=followed_user)
                        request.user.follows.add(followed_user)
                        messages.success(request, f'Vous êtes maintenant abonné à {followed_user}!')
                    except IntegrityError:
                        messages.error(request, f'Vous êtes déjà abonné à {followed_user}!')

            except User.DoesNotExist:
                messages.error(request, f'L\'utilisateur {follow_form.data["followed_user"]} n\'existe pas!')

    user_follows = request.user.follows.all()
    followed_by = UserFollows.objects.filter(followed_user=request.user).order_by('user')

    context = {
        'follow_form': follow_form,
        'followed_users': user_follows,
        'following_users': followed_by,
    }

    return render(request, 'reviews/follow_users.html', context=context)


@login_required
def unfollow_users(request, user_id):
    user = get_object_or_404(User, id=user_id)

    try:
        UserFollows.objects.get(user=request.user, followed_user=user).delete()
        request.user.follows.remove(user)
        messages.success(request, f'Vous vous êtes désabonné de {user}!')
    except UserFollows.DoesNotExist:
        messages.error(request, f'Vous n\'êtes pas abonné à {user}!')

    return redirect('reviews:follow_users')

reviews/templates/reviews/create_ticket.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl my-6">Créer un ticket</h2>

    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded">
        <form method="post" enctype="multipart/form-data">
            {{ ticket_form.as_p }}
            {% csrf_token %}
            <p class="flex justify-end">
                <button class="shadow-md border-solid border-2 p-2 border-sky-900 rounded bg-sky-900 hover:bg-sky-700 hover:shadow-none hover:border-sky-700 text-white mr-4"
                        type="submit">Envoyer</button>
            </p>
        </form>
    </div>

    <p>
        <a class="group" href="{% url 'reviews:home' %}">
            <svg xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24"
                 fill="currentColor"
                 class="w-6 h-6 inline-block">
                <path fill-rule="evenodd" d="M7.72 12.53a.75.75 0 010-1.06l7.5-7.5a.75.75 0 111.06 1.06L9.31 12l6.97 6.97a.75.75 0 11-1.06 1.06l-7.5-7.5z" clip-rule="evenodd" />
            </svg>
            <span class="group-hover:underline">Retour</span>
        </a>
    </p>
{% endblock content %}

reviews/templates/reviews/create_ticket_and_review.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl my-6">Créer une critique</h2>

    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded">
        <form method="post" enctype="multipart/form-data">
            <h3 class="text-xl my-6">Livre / Article</h3>

            {{ ticket_form.as_p }}

            <hr class="my-6" />

            <h3 class="text-xl my-6">Votre critique</h3>
            {{ review_form.as_p }}
            {% csrf_token %}
            <p class="flex justify-end">
                <button class="shadow-md border-solid border-2 p-2 border-sky-900 rounded bg-sky-900 hover:bg-sky-700 hover:shadow-none hover:border-sky-700 text-white mr-4"
                        type="submit">Envoyer</button>
            </p>
        </form>
    </div>

    <p>
        <a class="group" href="{% url 'reviews:home' %}">
            <svg xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24"
                 fill="currentColor"
                 class="w-6 h-6 inline-block">
                <path fill-rule="evenodd" d="M7.72 12.53a.75.75 0 010-1.06l7.5-7.5a.75.75 0 111.06 1.06L9.31 12l6.97 6.97a.75.75 0 11-1.06 1.06l-7.5-7.5z" clip-rule="evenodd" />
            </svg>
            <span class="group-hover:underline">Retour</span>
        </a>
    </p>
{% endblock content %}

reviews/templates/reviews/create_ticket_review.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl mb-6">Créer une critique</h2>

    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded">
        <div class="bg-slate-100 my-4 border-solid border border-slate-200 p-4 rounded">
            <p class="mb-4">Vous êtes en train de poster en réponse à :</p>
            {% include "reviews/partials/ticket_snippet.html" with ticket=ticket %}

        </div>

        <h3 class="text-xl my-6">Votre critique :</h3>

        {% if error_message %}
            <p>
                <strong>{{ error_message }}</strong>
            </p>
        {% endif %}

        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ review_form.as_p }}
            <p class="flex justify-end">
                <button class="shadow-md border-solid border-2 p-2 border-sky-900 rounded bg-sky-900 hover:bg-sky-700 hover:shadow-none hover:border-sky-700 text-white mr-4"
                        type="submit">Envoyer</button>
            </p>
        </form>

    </div>

    <p>
        <a class="group" href="{% url 'reviews:home' %}">
            <svg xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24"
                 fill="currentColor"
                 class="w-6 h-6 inline-block">
                <path fill-rule="evenodd" d="M7.72 12.53a.75.75 0 010-1.06l7.5-7.5a.75.75 0 111.06 1.06L9.31 12l6.97 6.97a.75.75 0 11-1.06 1.06l-7.5-7.5z" clip-rule="evenodd" />
            </svg>
            <span class="group-hover:underline">Retour</span>
        </a>
    </p>
{% endblock content %}

reviews/templates/reviews/delete_ticket.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl my-6">Supprimer un billet</h2>

    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded">
        <p>
            Vous êtes sur le point de supprimer le billet : <strong>{{ ticket.title }}</strong>
        </p>
        <p class="my-6">Êtes-vous sûr de vouloir supprimer ce billet ?</p>

        <form method="post">
            {{ delete_form }}
            {% csrf_token %}
            <p>
                <button class="shadow-md border-solid border-2 p-2 border-red-800 rounded bg-red-800 hover:bg-red-600 hover:shadow-none hover:border-red-600 text-white mr-4"
                        type="submit">Oui, je veux supprimer ce billet</button>

                <a class="group text-sky-900" href="{% url 'reviews:view_posts' %}">
                    <span class="group-hover:underline">Non, je ne veux pas supprimer ce billet</span>
                </a>
            </p>

        </form>
    </div>

    <p>
        <a class="group" href="{% url 'reviews:view_posts' %}">
            <svg xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24"
                 fill="currentColor"
                 class="w-6 h-6 inline-block">
                <path fill-rule="evenodd" d="M7.72 12.53a.75.75 0 010-1.06l7.5-7.5a.75.75 0 111.06 1.06L9.31 12l6.97 6.97a.75.75 0 11-1.06 1.06l-7.5-7.5z" clip-rule="evenodd" />
            </svg>
            <span class="group-hover:underline">Retour</span>
        </a>
    </p>
{% endblock content %}

reviews/templates/reviews/delete_ticket_review.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl my-6">Supprimer une critique</h2>

    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded">
        <p>
            Vous êtes sur le point de supprimer la critique : <strong>{{ review.headline }}</strong>
        </p>
        <p class="my-6">
            À propos de : <strong>{{ ticket.title }}</strong>
        </p>
        <p class="my-6">Êtes-vous sûr de vouloir supprimer ce billet ?</p>

        <form method="post">
            {{ delete_form }}
            {% csrf_token %}
            <button class="shadow-md border-solid border-2 p-2 border-red-800 rounded bg-red-800 hover:bg-red-600 hover:shadow-none hover:border-red-600 text-white mr-4"
                    type="submit">Oui, je veux supprimer cette critique</button>

            <a class="group text-sky-900" href="{% url 'reviews:view_posts' %}">
                <span class="group-hover:underline">Non, je ne veux pas supprimer cette critique</span>
            </a>
        </form>
    </div>

    <p>
        <a class="group" href="{% url 'reviews:view_posts' %}">
            <svg xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24"
                 fill="currentColor"
                 class="w-6 h-6 inline-block">
                <path fill-rule="evenodd" d="M7.72 12.53a.75.75 0 010-1.06l7.5-7.5a.75.75 0 111.06 1.06L9.31 12l6.97 6.97a.75.75 0 11-1.06 1.06l-7.5-7.5z" clip-rule="evenodd" />
            </svg>
            <span class="group-hover:underline">Retour</span>
        </a>
    </p>
{% endblock content %}

reviews/templates/reviews/edit_ticket.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl my-6">Modifier le billet</h2>

    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded">
        <form method="post" enctype="multipart/form-data">
            {{ edit_form.as_p }}
            {% csrf_token %}
            <p class="flex justify-end">
                <button class="shadow-md border-solid border-2 p-2 border-sky-900 rounded bg-sky-900 hover:bg-sky-700 hover:shadow-none hover:border-sky-700 text-white mr-4"
                        type="submit">Sauvegarder</button>
            </p>
        </form>
    </div>

    <p>
        <a class="group" href="{% url 'reviews:view_posts' %}">
            <svg xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24"
                 fill="currentColor"
                 class="w-6 h-6 inline-block">
                <path fill-rule="evenodd" d="M7.72 12.53a.75.75 0 010-1.06l7.5-7.5a.75.75 0 111.06 1.06L9.31 12l6.97 6.97a.75.75 0 11-1.06 1.06l-7.5-7.5z" clip-rule="evenodd" />
            </svg>
            <span class="group-hover:underline">Retour</span>
        </a>
    </p>
{% endblock content %}

reviews/templates/reviews/feed.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl my-6">Votre flux</h2>

    <div class="my-8">
        <a class="shadow-md border-solid border-2 p-2 border-sky-900 rounded bg-sky-900 hover:bg-sky-700 hover:shadow-none hover:border-sky-700 text-white mr-4"
           href="{% url 'reviews:create_ticket' %}">Demander une critique</a>

        <a class="border-solid border-2 p-2 border-sky-900 rounded hover:bg-sky-900/75 hover:text-white"
           href="{% url 'reviews:create_ticket_and_review' %}">Créer une critique</a>
    </div>

    {% for post in page_obj %}
        {% if post.content_type == 'TICKET' %}
            <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded">
                {% include "reviews/partials/ticket_snippet.html" with ticket=post %}

                {% if not post.has_reviewed %}
                    <div class="flex justify-end my-6">
                        <a class="shadow-md border-solid border-2 p-2 border-sky-900 rounded bg-sky-900 hover:bg-sky-700 hover:shadow-none hover:border-sky-700 text-white mr-4"
                           href="{% url 'reviews:create_ticket_review' post.id %}">Créer une critique</a>
                    </div>
                {% endif %}
            </div>

        {% elif post.content_type == 'REVIEW' %}
            <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded">
                {% include "reviews/partials/review_snippet.html" with review=post %}

            </div>

        {% endif %}

    {% endfor %}

    {% include "reviews/partials/paginator_snippet.html" %}

{% endblock content %}

reviews/templates/reviews/follow_users.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl my-6">Suivre d'autres utilisateurs</h2>

    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded">
        <form class="follow_users_form mb-6 mt-3 w-3/4" method="post">
            {{ follow_form.as_p }}
            {% csrf_token %}
            <button class="shadow-md border-solid border-2 p-2 border-sky-900 rounded bg-sky-900 hover:bg-sky-700 hover:shadow-none hover:border-sky-700 text-white mr-4"
                    type="submit">Confirmer</button>
        </form>

        <div class="flex">
            <div class="w-1/2 mr-4">
                <h3 class="text-xl my-4">Abonnements</h3>
                {% for followed_user in followed_users %}
                    <div class="flex items-center pb-2 mb-2 border-b border-slate-200 border-solid last:border-0">
                        {% include "reviews/partials/avatar_snippet.html" with user=followed_user %}

                        <p class="ml-2 w-full">{{ followed_user.username }}</p>
                        <a class="shadow-md border-solid border-2 p-1 border-red-800 rounded bg-red-800 hover:bg-red-600 hover:shadow-none hover:border-red-600 text-white"
                           href="{% url 'reviews:unfollow_users' followed_user.id %}">Désabonner</a>
                    </div>
                {% empty %}
                    <p>Vous ne suivez personne pour le moment.</p>
                {% endfor %}
            </div>

            <div class="border-solid border border-slate-200"></div>

            <div class="w-1/2 ml-4">
                <h3 class="text-xl my-4">Abonnés</h3>
                {% for following_user in following_users %}
                    <div class="flex items-center pb-2 mb-2 border-b border-slate-200 border-solid last:border-0">
                        {% include "reviews/partials/avatar_snippet.html" with user=following_user.user %}

                        <p class="ml-2">{{ following_user.user.username }}</p>
                    </div>
                {% empty %}
                    <p>Personne ne vous suit pour le moment.</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

reviews/templates/reviews/posts.html
{% extends "base.html" %}

{% load reviews_extras %}

{% block content %}
    <h2 class="text-2xl my-6">Vos posts</h2>

    {% if page_obj %}
        {% for post in page_obj %}
            {% if post.content_type == 'TICKET' %}
                <div class="ticket bg-white my-4 border-solid border border-slate-200 p-4 rounded">
                    {% include "reviews/partials/ticket_snippet.html" with ticket=post %}

                    <div class="flex justify-end my-6">
                        <a class="shadow-md border-solid border-2 p-2 border-sky-900 rounded bg-sky-900 hover:bg-sky-700 hover:shadow-none hover:border-sky-700 text-white mr-4"
                           href="{% url 'reviews:edit_ticket' post.id %}">Modifier</a>
                        <a class="shadow-md border-solid border-2 p-2 border-red-800 rounded bg-red-800 hover:bg-red-600 hover:shadow-none hover:border-red-600 text-white mr-4"
                           href="{% url 'reviews:delete_ticket' post.id %}">Supprimer</a>
                    </div>
                </div>

            {% elif post.content_type == 'REVIEW' %}
                <div class="ticket bg-white my-4 border-solid border border-slate-200 p-4 rounded">
                    {% include "reviews/partials/review_snippet.html" with review=post %}

                    <div class="flex justify-end my-6">
                        <a class="shadow-md border-solid border-2 p-2 border-sky-900 rounded bg-sky-900 hover:bg-sky-700 hover:shadow-none hover:border-sky-700 text-white mr-4"
                           href="{% url 'reviews:edit_ticket_review' post.ticket.id post.id %}">Modifier</a>
                        <a class="shadow-md border-solid border-2 p-2 border-red-800 rounded bg-red-800 hover:bg-red-600 hover:shadow-none hover:border-red-600 text-white mr-4"
                           href="{% url 'reviews:delete_ticket_review' post.ticket.id post.id %}">Supprimer</a>
                    </div>
                </div>

            {% endif %}

        {% endfor %}

        {% include "reviews/partials/paginator_snippet.html" %}

    {% else %}
        <p>Vous n'avez créé aucun post pour le moment</p>
    {% endif %}
{% endblock content %}