authentication/urls.py
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path

from . import views

# Namespace for the authentication app
app_name = 'authentication'

urlpatterns = [
    path(
        '',
        LoginView.as_view(template_name='authentication/login.html', redirect_authenticated_user=True),
        name='login',
    ),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup_page, name='signup'),
    path(
        'change-password/',
        PasswordChangeView.as_view(template_name='authentication/change_password.html'),
        name='password_change',
    ),
    path(
        'change-password-done/',
        PasswordChangeDoneView.as_view(template_name='authentication/change_password_done.html'),
        name='password_change_done',
    ),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

litrevu/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("reviews.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path

from . import views

# Namespace for the reviews app
app_name = 'reviews'

urlpatterns = [
    path('feed/', views.feed, name='home'),
    path('posts/', views.view_posts, name='view_posts'),
    path('tickets/create/', views.create_ticket, name='create_ticket'),
    path('tickets/<int:ticket_id>/edit/', views.edit_ticket, name='edit_ticket'),
    path('tickets/<int:ticket_id>/delete/', views.delete_ticket, name='delete_ticket'),
    path('tickets/<int:ticket_id>/reviews/create', views.create_ticket_review, name='create_ticket_review'),
    path('tickets/<int:ticket_id>/reviews/<int:review_id>/edit/', views.edit_ticket_review, name='edit_ticket_review'),
    path(
        'tickets/<int:ticket_id>/reviews/<int:review_id>/delete/',
        views.delete_ticket_review,
        name='delete_ticket_review',
    ),
    path('tickets-reviews/create/', views.create_ticket_and_review, name='create_ticket_and_review'),
    path('follow_users/', views.follow_users, name='follow_users'),
    path('unfollow_users/<int:user_id>', views.unfollow_users, name='unfollow_users'),
]

authentication/models.py
from django.contrib.auth.models import AbstractUser, Group
from django.db import models
from django.conf import settings


class User(AbstractUser):
    '''
    User model for authentication.
    It is an extension of the AbstractUser model.
    It is used to store the user's profile photo and role.
    '''

    CREATOR = 'CREATOR'
    SUBSCRIBER = 'SUBSCRIBER'

    ROLE_CHOICES = (
        (CREATOR, 'Créateur'),
        (SUBSCRIBER, 'Abonné'),
    )
    profile_photo = models.ImageField(verbose_name='Photo de profil', null=True, blank=True)
    role = models.CharField(max_length=30, choices=ROLE_CHOICES, verbose_name='Rôle', default=CREATOR)
    follows = models.ManyToManyField(
        "self", limit_choices_to={'role': CREATOR}, symmetrical=False, verbose_name="suit"
    )

    def assign_permissions(self):
        if self.role == self.CREATOR:
            group = Group.objects.get(name='creators')
            group.user_set.add(self)
        elif self.role == self.SUBSCRIBER:
            group = Group.objects.get(name='subscribers')
            group.user_set.add(self)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.assign_permissions()


class UserFollows(models.Model):
    '''
    Model for a user following another user.

    Attributes:
        user (ForeignKey): The user who is following another user.
        followed_user (ForeignKey): The user who is being followed.
    '''

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="following")
    followed_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="followed_by")

    class Meta:
        # a user can only follow another user once
        constraints = [models.UniqueConstraint(fields=["user", "followed_user"], name="unique_follow")]

authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class SignupForm(UserCreationForm):
    '''
    Form for signing up a new user.
    '''

    class Meta(UserCreationForm.Meta):
        '''
        Meta class for SignupForm.

        Attributes:
            model (User): The user model.
            fields (tuple): The fields to display in the form.
        '''

        model = get_user_model()
        fields = ('username',)


class EditProfileForm(forms.ModelForm):
    '''
    Form for editing a user's profile.
    '''

    # Profile photo is optional
    profile_photo = forms.ImageField(required=False)

    class Meta:
        '''
        Meta class for EditProfileForm.

        Attributes:
            model (User): The user model.
            fields (tuple): The fields to display in the form.
        '''

        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_photo')

authentication/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout

from . import forms


def signup_page(request):
    '''
    View for the signup page.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The response object.
    '''

    form = forms.SignupForm()
    if request.method == "POST":
        form = forms.SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            # auto-login user
            login(request, user)
            return redirect(settings.LOGIN_REDIRECT_URL)

    return render(request, "authentication/signup.html", {"form": form})


def edit_profile(request):
    '''
    View for the edit profile page.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The response object.
    '''

    form = forms.EditProfileForm(instance=request.user)

    if request.method == "POST":
        form = forms.EditProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return render(request, "authentication/edit_profile_done.html")

    return render(request, "authentication/edit_profile.html", {"form": form})


def logout_user(request):
    '''
    View for logging out a user.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The response object.
    '''

    logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)

authentication/templates/authentication/change_password.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl my-6">Modifier mon mot de passe</h2>

    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded sm:w-3/5 sm:mx-auto">
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p class="flex justify-end">
                <button class="shadow-md border-solid border-2 p-2 border-sky-900 rounded bg-sky-900 hover:bg-sky-700 hover:shadow-none hover:border-sky-700 text-white mr-4"
                        type="submit">Modifier</button>
            </p>
        </form>
    </div>

    <p>
        <a class="group" href="{% url 'reviews:home' %}">
            <svg xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24"
                 fill="currentColor"
                 class="w-6 h-6 inline-block">
                <path fill-rule="evenodd" d="M7.72 12.53a.75.75 0 010-1.06l7.5-7.5a.75.75 0 111.06 1.06L9.31 12l6.97 6.97a.75.75 0 11-1.06 1.06l-7.5-7.5z" clip-rule="evenodd" />
            </svg>
            <span class="group-hover:underline">Retour</span>
        </a>
    </p>
{% endblock content %}

authentication/templates/authentication/change_password_done.html
{% extends "base.html" %}

{% block content %}
    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded sm:w-3/5 sm:mx-auto">
        <p>
            Vous avez changé votre mot de passe avec succès ! Cliquez <a href={% url 'reviews:home' %}>ici</a> pour revenir à la page d’accueil.
        </p>
    </div>
{% endblock content %}

authentication/templates/authentication/edit_profile.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl my-6">Modifier votre profil</h2>

    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded sm:w-3/5 sm:mx-auto">
        <form method="post" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <p class="flex justify-end">
                <button class="shadow-md border-solid border-2 p-2 border-sky-900 rounded bg-sky-900 hover:bg-sky-700 hover:shadow-none hover:border-sky-700 text-white mr-4"
                        type="submit">Modifier</button>
            </p>
        </form>
    </div>

    <p>
        <a class="group" href="{% url 'reviews:home' %}">
            <svg xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24"
                 fill="currentColor"
                 class="w-6 h-6 inline-block">
                <path fill-rule="evenodd" d="M7.72 12.53a.75.75 0 010-1.06l7.5-7.5a.75.75 0 111.06 1.06L9.31 12l6.97 6.97a.75.75 0 11-1.06 1.06l-7.5-7.5z" clip-rule="evenodd" />
            </svg>
            <span class="group-hover:underline">Retour</span>
        </a>
    </p>
{% endblock content %}

authentication/templates/authentication/edit_profile_done.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl my-6">Modifier votre profil</h2>

    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded sm:w-3/5 sm:mx-auto">
        <p>
            Vous avez modifié votre profil avec succès ! Cliquez <a class="font-bold hover:underline" href={% url 'reviews:home' %}>ici</a> pour revenir à la page d’accueil.
        </p>
    </div>

    <p>
        <a class="group" href="{% url 'reviews:home' %}">
            <svg xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24"
                 fill="currentColor"
                 class="w-6 h-6 inline-block">
                <path fill-rule="evenodd" d="M7.72 12.53a.75.75 0 010-1.06l7.5-7.5a.75.75 0 111.06 1.06L9.31 12l6.97 6.97a.75.75 0 11-1.06 1.06l-7.5-7.5z" clip-rule="evenodd" />
            </svg>
            <span class="group-hover:underline">Retour</span>
        </a>
    </p>
{% endblock content %}

authentication/templates/authentication/login.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl my-6">Connectez-vous</h2>

    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded sm:w-3/5 sm:mx-auto">
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p class="flex justify-end">
                <button class="shadow-md border-solid border-2 p-2 border-sky-900 rounded bg-sky-900 hover:bg-sky-700 hover:shadow-none hover:border-sky-700 text-white mr-4"
                        type="submit">Se connecter</button>
            </p>
        </form>
        <p>
            Pas encore membre ? <a class="hover:underline" href={% url 'authentication:signup' %}>Inscrivez-vous maintenant !</a>
        </p>
    </div>
{% endblock content %}

authentication/templates/authentication/signup.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl my-6">Inscrivez-vous</h2>

    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded sm:w-3/5 sm:mx-auto">
        {% if form.errors %}{{ form.errors }}{% endif %}
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p class="flex justify-end">
                <button class="shadow-md border-solid border-2 p-2 border-sky-900 rounded bg-sky-900 hover:bg-sky-700 hover:shadow-none hover:border-sky-700 text-white mr-4"
                        type="submit">S'inscrire</button>
            </p>
        </form>
    </div>

    <p>
        <a class="group" href="{% url 'authentication:login' %}">
            <svg xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24"
                 fill="currentColor"
                 class="w-6 h-6 inline-block">
                <path fill-rule="evenodd" d="M7.72 12.53a.75.75 0 010-1.06l7.5-7.5a.75.75 0 111.06 1.06L9.31 12l6.97 6.97a.75.75 0 11-1.06 1.06l-7.5-7.5z" clip-rule="evenodd" />
            </svg>
            <span class="group-hover:underline">Retour</span>
        </a>
    </p>
{% endblock content %}

authentication/templates/authentication/upload_profile_picture.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl my-6">Télécharger une photo de profil</h2>

    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded sm:w-3/5 sm:mx-auto">
        <form method="post" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <p class="flex justify-end">
                <button class="shadow-md border-solid border-2 p-2 border-sky-900 rounded bg-sky-900 hover:bg-sky-700 hover:shadow-none hover:border-sky-700 text-white mr-4"
                        type="submit">Télécharger</button>
            </p>
        </form>
    </div>

    <p>
        <a class="group" href="{% url 'home' %}">
            <svg xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24"
                 fill="currentColor"
                 class="w-6 h-6 inline-block">
                <path fill-rule="evenodd" d="M7.72 12.53a.75.75 0 010-1.06l7.5-7.5a.75.75 0 111.06 1.06L9.31 12l6.97 6.97a.75.75 0 11-1.06 1.06l-7.5-7.5z" clip-rule="evenodd" />
            </svg>
            <span class="group-hover:underline">Retour</span>
        </a>
    </p>
{% endblock content %}

authentication/templates/authentication/upload_profile_picture_done.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-2xl my-6">Télécharger une photo de profil</h2>

    <div class="bg-white my-4 border-solid border border-slate-200 p-4 rounded sm:w-3/5 sm:mx-auto">
        <p>
            Vous avez changé votre photo de profil avec succès ! Cliquez <a class="font-bold hover:underline" href={% url 'home' %}>ici</a> pour revenir à la page d’accueil.
        </p>
    </div>

    <p>
        <a class="group" href="{% url 'home' %}">
            <svg xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24"
                 fill="currentColor"
                 class="w-6 h-6 inline-block">
                <path fill-rule="evenodd" d="M7.72 12.53a.75.75 0 010-1.06l7.5-7.5a.75.75 0 111.06 1.06L9.31 12l6.97 6.97a.75.75 0 11-1.06 1.06l-7.5-7.5z" clip-rule="evenodd" />
            </svg>
            <span class="group-hover:underline">Retour</span>
        </a>
    </p>
{% endblock content %}