authentication/urls.py
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path

from . import views

# Namespace for the authentication app
app_name = 'authentication'

urlpatterns = [
    path(
        '',
        LoginView.as_view(template_name='authentication/login.html', redirect_authenticated_user=True),
        name='login',
    ),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup_page, name='signup'),
    path(
        'change-password/',
        PasswordChangeView.as_view(template_name='authentication/change_password.html'),
        name='password_change',
    ),
    path(
        'change-password-done/',
        PasswordChangeDoneView.as_view(template_name='authentication/change_password_done.html'),
        name='password_change_done',
    ),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

litrevu/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("reviews.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path

from . import views

# Namespace for the reviews app
app_name = 'reviews'

urlpatterns = [
    path('feed/', views.feed, name='home'),
    path('posts/', views.view_posts, name='view_posts'),
    path('tickets/create/', views.create_ticket, name='create_ticket'),
    path('tickets/<int:ticket_id>/edit/', views.edit_ticket, name='edit_ticket'),
    path('tickets/<int:ticket_id>/delete/', views.delete_ticket, name='delete_ticket'),
    path('tickets/<int:ticket_id>/reviews/create', views.create_ticket_review, name='create_ticket_review'),
    path('tickets/<int:ticket_id>/reviews/<int:review_id>/edit/', views.edit_ticket_review, name='edit_ticket_review'),
    path(
        'tickets/<int:ticket_id>/reviews/<int:review_id>/delete/',
        views.delete_ticket_review,
        name='delete_ticket_review',
    ),
    path('tickets-reviews/create/', views.create_ticket_and_review, name='create_ticket_and_review'),
    path('follow_users/', views.follow_users, name='follow_users'),
    path('unfollow_users/<int:user_id>', views.unfollow_users, name='unfollow_users'),
]

templates/base.html
{% load static %}
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="fr">
    <head>
        <title>LitRevu</title>
        <meta charset="utf-8" />
        <meta name="description" content="LitRevu" />
        <meta name="keywords" content="LitRevu" />
        <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
        <link rel="icon" href="{% static 'assets/images/favicon.ico' %}" />
        {% tailwind_css %}
    </head>

    <body class="bg-slate-100 font-sans text-base">
        <header class="flex justify-between items-center bg-sky-900 text-white mb-8 px-4 py-2">
            <a href="{% url 'reviews:home' %}">
                <div class="flex">
                    <img width="40px"
                         height="40px"
                         src="{% static 'assets/images/logo_litrevu.png' %}"
                         alt="Logo de LitRevu" />
                    <h1 class="text-4xl ml-2">LitRevu</h1>
                </div>
            </a>

            {% if user.is_authenticated %}
                <nav>
                    <ul class="flex justify-between items-center">
                        <li class="p-2">
                            <a class="hover:underline" href={% url 'reviews:home' %}>Flux</a>
                        </li>
                        <li class="p-2">
                            <a class="hover:underline" href={% url 'reviews:view_posts' %}>Posts</a>
                        </li>
                        <li class="p-2">
                            <a class="hover:underline" href={% url 'reviews:follow_users' %}>Abonnements</a>
                        </li>
                        <li class="p-2 relative group">
                            <a href="#">
                                {% include "reviews/partials/avatar_snippet.html" with user=request.user %}

                            </a>
                            <ul class="bg-sky-900 absolute right-0 top-14 w-max hidden group-hover:block">
                                <li class="p-2">
                                    <span class="font-bold text-white">Welcome {{ request.user.username }} !</span>
                                </li>
                                <li class="p-2">
                                    <a class="hover:underline" href={% url 'authentication:edit_profile' %}>Modifier votre profil</a>
                                </li>
                                <li class="p-2">
                                    <a class="hover:underline"
                                       href="{% url 'authentication:password_change' %}">Modifier le mot de passe</a>
                                </li>
                                <li class="p-2">
                                    <a class="hover:underline" href={% url 'authentication:logout' %}>Se déconnecter</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            {% endif %}
        </header>

        <main class="container mx-auto min-h-screen">
            {% if messages %}
                {% for message in messages %}
                    <div class="messages absolute bottom-0 {% if message.tags == 'error' %}bg-red-100 border border-red-400 text-red-700{% endif %} {% if message.tags == 'success' %}bg-green-100 border border-green-400 text-green-700{% endif %} {% if message.tags == 'info' %}bg-blue-100 border border-blue-400 text-blue-700{% endif %} {% if message.tags == 'warning' %}bg-yellow-100 border border-yellow-400 text-yellow-700{% endif %} p-4 mb-4 rounded-lg">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <div>
                {% block content %}
                {% endblock content %}
            </div>
        </main>

        <footer class="flex justify-center bg-sky-900 text-white p-2 mt-8">
            <p>© 2023 LitRevu - Grégory Lama</p>
        </footer>
    </body>

    <script>
        // JavaScript pour masquer les messages Django après un délai de 5 secondes
        document.addEventListener('DOMContentLoaded', function() {
            const messages = document.querySelectorAll('.messages');
            if (messages) {
                messages.forEach(function(message) {
                    setTimeout(function() {
                        message.style.display = 'none';
                    }, 5000); // Masquer après 5 secondes (5000 millisecondes)
                });
            }
        });
    </script>
</html>